name: Deploy-Self-Hosted

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /var/www/vanillix
          git pull
          composer install --no-dev
          
